### ISSUE TITLE
Issue importing qApp

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#105]
```
Traceback (most recent call last):
  File "/home/laura/miniconda3/envs/idvc/bin/idvc", line 6, in <module>
    from idvc.dvc_interface import main
  File "/home/laura/miniconda3/envs/idvc/lib/python3.7/site-packages/idvc/dvc_interface.py", line 7, in <module>
    from PySide2.QtWidgets import (QAction, QCheckBox, QComboBox,
ImportError: cannot import name 'qApp' from 'PySide2.QtWidgets' (/home/laura/miniconda3/envs/idvc/lib/python3.7/site-packages/PySide2/QtWidgets.cpython-37m-x86_64-linux-gnu.so)

```

https://bugreports.qt.io/browse/PYSIDE-1382

Looks like we just need to import PySide2 instead?

**Comment by lauramurgatroyd** [comment]
This is an issue on both linux and windows
