### ISSUE TITLE
Run DVC  error in version 24.0.1

### ISSUE THREAD

**Issue by ET06731** [TomographicImaging/iDVC#319]
points in mask 1574
finished 1/1 (or 1) with 0 PySide2.QtCore.QProcess.ExitStatus.NormalExit
all OK, all processes ended
Traceback (most recent call last):
  File "E:\worksoftware\anaconda\envs\idvc_environment\Lib\site-packages\idvc\dvc_interface.py", line 4961, in show_run_pcs
    result = RunResults(file_path)
             ^^^^^^^^^^^^^^^^^^^^^
  File "E:\worksoftware\anaconda\envs\idvc_environment\Lib\site-packages\idvc\utilities.py", line 18, in __init__
    with open(stat_file_name,"r") as stat_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\system32\\DVC_Sessions\\tmpibitdqli\\Results\\11\\dvc_result_0\\dvc_result_0.stat'
Traceback (most recent call last):
  File "E:\worksoftware\anaconda\envs\idvc_environment\Lib\site-packages\idvc\dvc_runner.py", line 517, in finished_run
    finish_fn()
    ^^^^^^^^^^^
  File "E:\worksoftware\anaconda\envs\idvc_environment\Lib\site-packages\idvc\dvc_interface.py", line 4796, in finished_run
    self.show_run_pcs()
  File "E:\worksoftware\anaconda\envs\idvc_environment\Lib\site-packages\idvc\dvc_interface.py", line 4961, in show_run_pcs
    result = RunResults(file_path)
             ^^^^^^^^^^^^^^^^^^^^^
  File "E:\worksoftware\anaconda\envs\idvc_environment\Lib\site-packages\idvc\utilities.py", line 18, in __init__
    with open(stat_file_name,"r") as stat_file:

**Comment by DanicaSTFC** [comment]
Hi, 

Thank you for opening the issue. Unfortunately, even though the dialog says that you analysis ran successfully, this was not the case. The actual error must have happened before. Could you provide more information on the data and point cloud you are using?

Best,

Danica

**Comment by ET06731** [comment]
Sorry, due to confidentiality restrictions, I are not able to provide the data.The images I input are image sequences in tiff format. It is converted to a raw file before performing DVC run and is not analyzed but shows that the analysis is running successfully. I tried to use the converted raw file as input and the DVC runs actually worked. 
Thank you for your respond and your work. 
Additional error messages are reported as follows
`Traceback (most recent call last):
  File "E:\Worksoftware\Anaconda\envs\idvc1\Lib\site-packages\idvc\dvc_interface.py", line 3207, in select_pointcloud
    shutil.copyfile(self.roi, os.path.join(tempfile.tempdir, filename))
  File "E:\Worksoftware\Anaconda\envs\idvc1\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
points in mask 2536
finished 1/1 (or 1) with 0 PySide2.QtCore.QProcess.ExitStatus.NormalExit
all OK, all processes ended`

**Comment by DanicaSTFC** [comment]
I will now close this issue. If you have any further question feel free to contact us again. 

Thank you.

The iDVC team.
