### ISSUE TITLE
Can't view graphs of DVC results

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#52]
Error:

```
Traceback (most recent call last):
  File "C:\Users\lhe97136\Miniconda3\envs\dvc_app_dev\lib\site-packages\idvc\dvc_interface.py", line 4235, in CreateGraphsWindow
    self.graph_window.CreateDockWidgets()
  File "C:\Users\lhe97136\Miniconda3\envs\dvc_app_dev\lib\site-packages\idvc\dvc_interface.py", line 5453, in CreateDockWidgets
    GraphWidget = SingleRunResultsWidget(self, result, plot_titles, displ_wrt_point0)
  File "C:\Users\lhe97136\Miniconda3\envs\dvc_app_dev\lib\site-packages\idvc\dvc_interface.py", line 5495, in __init__
    self.CreateHistogram(plot_data, plot_titles, displ_wrt_point0)
  File "C:\Users\lhe97136\Miniconda3\envs\dvc_app_dev\lib\site-packages\idvc\dvc_interface.py", line 5518, in CreateHistogram
    phi_disp = displ[:, 9]
IndexError: index 9 is out of bounds for axis 1 with size 9
```

This is related to reading the displacement file resulting from running the DVC analysis - it suggests the 10th column in the file doesn't exist

**Comment by lauramurgatroyd** [comment]
This error is due to the fact that the displacement file no longer has theta, phi and psi

![image](https://user-images.githubusercontent.com/60604372/129219781-bb29007e-0dd9-4e3c-9417-19305e04bfb8.png)

**Comment by lauramurgatroyd** [comment]
This change was introduced in this PR: https://github.com/vais-ral/CCPi-DVC/pull/133/files so should mean this error only occurs in v21.1.1 of iDVC

**Comment by lauramurgatroyd** [comment]
Related change: https://github.com/vais-ral/CCPi-DVC/blob/660a623df5e562e263a451ccd9c6b434db23ce6a/Core/InputRead.cpp#L1124-L1136
